# Generated by Django 5.0.7 on 2024-07-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_terms_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
