# Generated by Django 5.0.7 on 2024-07-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usertokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTokens',
        ),
    ]
